version: '3'

services:
  app:
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - "1234:1234"
    environment:
      FLAG: BSIDES{t1m3_m4g1c}
    networks:
      - sneaky_channels

networks:
  sneaky_channels:
