version: '3'

services:
  app:
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - "4141:4141"
    environment:
      FLAG: BSIDES{4lWay5_uS3_p4dd1Ng}
    networks:
      - student_life

networks:
  student_life:
